exclude: |
  (?x)
  # NOTA: Agrega aquí exclusiones específicas si es necesario
  # files/to/exclude/

default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
      - id: check-yaml
      - id: check-xml
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: ["--profile", "black"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify

  - repo: https://github.com/OCA/pylint-odoo
    rev: v8.0.20
    hooks:
      - id: pylint_odoo
        name: pylint_odoo
        args: ["-d", "all", "-e", "odoo"]
