from odoo import api, fields, models, _
from odoo.exceptions import UserError, ValidationError

class Contract(models.Model):
    _inherit = "contract.contract"

    # Nomenclatura Genérica: En lugar de usar términos de "factura" en el código custom, 
    # preferimos términos genéricos.
    recurring_invoicing_type = fields.Selection(
        [
            ("pre-paid", "Al inicio del periodo"),
            ("post-paid", "Al finalizar el periodo"),
        ],
        string="Momento de Generación",
        default="pre-paid",
        required=True,
    )
    
    recurring_next_date = fields.Date(string="Próxima Generación")
    last_date_invoiced = fields.Date(string="Última Generación")
    
    auto_post_invoice = fields.Boolean(
        string="Validar Facturas Automáticamente",
        default=True,
        help="Si está marcado, las facturas generadas por este contrato se publicarán automáticamente."
    )
    
    sale_autoconfirm = fields.Boolean(
        string="Auto confirmar el pedido de venta",
        default=True,
        help="Si está marcado, los pedidos de venta generados por este contrato se confirmarán automáticamente."
    )
    
    name = fields.Char(default=lambda self: _('New'), copy=False, readonly=True)

    state = fields.Selection([
        ('draft', 'Borrador'),
        ('in_progress', 'En Curso'),
        ('done', 'Finalizado'),
        ('cancelled', 'Cancelado')
    ], string='Estado', default='draft', tracking=True)

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', _('New')) == _('New') or not vals.get('name'):
                # Determinar el prefijo según el tipo de contrato y generación
                c_type = vals.get('contract_type', self.env.context.get('default_contract_type', 'sale'))
                g_type = vals.get('generation_type', self.env.context.get('default_generation_type', 'invoice'))
                
                if c_type == 'sale':
                    prefix = 'CIV-' if g_type == 'invoice' else 'CSO-'
                else:
                    prefix = 'CIP-' if g_type == 'invoice' else 'CPO-'
                
                # Obtener el siguiente número de la secuencia universal (ej. 2026/0001)
                sequence_number = self.env['ir.sequence'].next_by_code('contract.contract') or ''
                vals['name'] = f"{prefix}{sequence_number}" if sequence_number else _('New')
        return super().create(vals_list)

    # Bloqueamos el cambio de plantilla si no es borrador y emulamos la protección de ventas
    safe_template_id = fields.Many2one(
        "contract.template", 
        string="Plantilla de Contrato",
    )

    @api.onchange('safe_template_id')
    def _onchange_safe_template_id(self):
        if not self.safe_template_id:
            return
            
        if self.contract_line_ids:
            template = self.safe_template_id
            self.safe_template_id = False
            return {
                'warning': {
                    'title': _('Atención'),
                    'message': _('El contrato ya tiene líneas. Haga clic en "Aplicar Plantilla" si desea reemplazar o fusionar sus líneas actuales.')
                }
            }
        else:
            self.contract_template_id = self.safe_template_id
            self.safe_template_id = False

    def action_in_progress(self):
        for rec in self:
            rec.state = 'in_progress'

    def action_draft(self):
        for rec in self:
            rec.state = 'draft'

    def action_cancel(self):
        for rec in self:
            rec.state = 'cancelled'

    def action_open_template_wizard(self):
        self.ensure_one()
        # TODO: Lógica para reutilizar el wizard de plantillas de ventas
        pass

    # Campo emulado para Proveedores (Oculta la opción Sale)
    purchase_generation_type = fields.Selection(
        [('invoice', 'Invoice')],
        string="Generation Type",
        help="Defines what document is automatically generated by the cron.",
        required=True,
        compute="_compute_purchase_generation_type",
        inverse="_inverse_purchase_generation_type"
    )

    @api.depends('generation_type')
    def _compute_purchase_generation_type(self):
        for rec in self:
            rec.purchase_generation_type = 'invoice'

    def _inverse_purchase_generation_type(self):
        for rec in self:
            if rec.contract_type == 'purchase':
                rec.generation_type = 'invoice'

    # Campo emulado para Clientes (Mantiene simetría y lo hace obligatorio)
    sale_generation_type = fields.Selection(
        [('sale', 'Sale'), ('invoice', 'Invoice')],
        string="Generation Type",
        help="Defines what document is automatically generated by the cron.",
        required=True,
        compute="_compute_sale_generation_type",
        inverse="_inverse_sale_generation_type"
    )

    @api.depends('generation_type')
    def _compute_sale_generation_type(self):
        for rec in self:
            rec.sale_generation_type = rec.generation_type or 'invoice'

    def _inverse_sale_generation_type(self):
        for rec in self:
            if rec.contract_type == 'sale':
                rec.generation_type = rec.sale_generation_type

    @api.constrains('generation_type', 'contract_type')
    def _check_generation_type_allowed(self):
        for rec in self:
            if rec.contract_type == 'sale':
                if rec.generation_type == 'invoice' and not self.env.user.has_group('contract_management.group_contract_sale_invoice'):
                    raise ValidationError(_("La generación de Facturas de Venta está desactivada en la Configuración Global."))
                if rec.generation_type == 'sale' and not self.env.user.has_group('contract_management.group_contract_sale_order'):
                    raise ValidationError(_("La generación de Pedidos de Venta está desactivada en la Configuración Global."))
            elif rec.contract_type == 'purchase':
                if rec.generation_type == 'invoice' and not self.env.user.has_group('contract_management.group_contract_purchase_invoice'):
                    raise ValidationError(_("La generación de Facturas de Compra está desactivada en la Configuración Global."))

    # --- Leyenda Dinámica de Periodo ---
    add_period_legend = fields.Boolean(
        string="Agregar leyenda de periodo",
        default=False
    )
    period_legend_text = fields.Char(
        string="Texto Previo",
        help="Ej: 'Periodo facturado:'. Se omitirá si se deja vacío."
    )
    period_legend_type = fields.Selection(
        [('period', 'Periodo'), ('month', 'Mes')],
        string="Tipo de Leyenda",
        default='period'
    )
    period_legend_location = fields.Selection(
        [('product', 'Concatenada al producto'), ('note', 'En una nota')],
        string="Lugar de la Leyenda",
        default='product'
    )

    def _get_legend_string(self, legend_type):
        base_marker = ""
        if legend_type == 'period':
            base_marker = "#START# al #END#"
        elif legend_type == 'month':
            base_marker = "#INVOICEMONTHNAME#"
            
        if not base_marker:
            return ""
            
        if self.period_legend_text:
            return f"{self.period_legend_text.strip()} {base_marker}"
        return base_marker

    @api.onchange('add_period_legend', 'period_legend_type', 'period_legend_location', 'period_legend_text')
    def _onchange_period_legend(self):
        import re
        for rec in self:
            # Primero identificamos las notas de leyenda actuales
            legend_notes = rec.contract_line_ids.filtered(
                lambda l: l.display_type == 'line_note' and l.name and 
                ("#START#" in l.name or "#INVOICEMONTHNAME#" in l.name)
            )

            # Las eliminamos del RecordSet (esto limpia la UI inmediatamente)
            if legend_notes:
                rec.contract_line_ids -= legend_notes

            # Limpiamos los sufijos de los productos normales
            for line in rec.contract_line_ids.filtered(lambda l: not l.display_type):
                if line.name:
                    line.name = re.sub(r' - .*?(#START# al #END#|#INVOICEMONTHNAME#)$', '', line.name)

            # Si la leyenda está activa, aplicamos la nueva configuración
            if rec.add_period_legend:
                legend_str = rec._get_legend_string(rec.period_legend_type)
                if legend_str:
                    if rec.period_legend_location == 'product':
                        # Concatenamos a los productos
                        for line in rec.contract_line_ids.filtered(lambda l: not l.display_type):
                            if line.name:
                                line.name = f"{line.name} - {legend_str}"
                    
                    elif rec.period_legend_location == 'note':
                        # Agregamos una nueva nota pura usando .new()
                        max_seq = max(rec.contract_line_ids.mapped('sequence')) if rec.contract_line_ids else 10
                        rec.contract_line_ids += self.env['contract.line'].new({
                            'display_type': 'line_note',
                            'name': legend_str,
                            'sequence': max_seq + 1,
                        })

    def write(self, vals):
        res = super().write(vals)
        # Asegurar que si la leyenda es tipo nota, siempre esté al final (mayor secuencia)
        for rec in self:
            if rec.add_period_legend and rec.period_legend_location == 'note':
                legend_note = rec.contract_line_ids.filtered(
                    lambda l: l.display_type == 'line_note' and l.name and
                    ("#START# al #END#" in l.name or "#INVOICEMONTHNAME#" in l.name)
                )
                if legend_note:
                    max_seq = max(rec.contract_line_ids.filtered(lambda l: l.id != legend_note[0].id).mapped('sequence')) if len(rec.contract_line_ids) > 1 else 10
                    if legend_note[0].sequence <= max_seq:
                        legend_note[0].sequence = max_seq + 1
        return res

    # Extensión del Cron: Para evitar que Odoo genere documentos de contratos en borrador,
    # debemos filtrar en el dominio o sobreescribir el método de búsqueda de generación.
    # En la OCA, generalmente el método base es `_get_contracts_to_invoice()`.
    
    @api.model
    def _get_contracts_to_invoice_domain(self):
        """ Sobrescribimos el dominio del cron para ignorar borradores """
        # La forma exacta depende de la versión OCA, pero este es el dominio base
        domain = super()._get_contracts_to_invoice_domain()
        domain.append(('state', '=', 'in_progress'))
        return domain

    def _recurring_create_invoice(self, date_ref=False):
        moves = super()._recurring_create_invoice(date_ref=date_ref)
        for move in moves.filtered("invoice_line_ids"):
            contracts = move.invoice_line_ids.mapped('contract_line_id.contract_id')
            if any(c.auto_post_invoice for c in contracts):
                move.action_post()
        return moves
